### ISSUE TITLE
Bookmarks annoying to make

### ISSUE THREAD

**Issue by Tearony** [Goodwy/Discussion#2]
As the bookmarks are annoying to make I'd like to request an option for setting a standard name.
For example: <Bookmark Number><tim><date>
It would rally help me because I don't care about the name of my bookmark if it just brings me to the point where I stopped listening. You could just make it so you can change the name afterwards. Thanks for your attention.

Thanks for your great work,
keep it up.

**Comment by Goodwy** [comment]
Hello.
If you mean bookmarks in the PlayBooks application, then to create a quick bookmark, just perform a long tap on the bookmark button in the player. Without distracting you with additional actions, a bookmark with a standard name will be created.
