### ISSUE TITLE
[FEATURE] Many features for better app

### ISSUE THREAD

**Issue by heckarman** [Goodwy/Discussion#4]
First of all, hey Goodwy! Thanks for this amazing project and I'm fairly new to Android app development and would love to contribute in my free time.

Some of the amazing features that would be great to see in the apps which could get basics perfect:
- Dialer
  - Call recording (BCR call recording app is one of the app that we can refer to but that requires root access to be existent)
  - Spam detection (One of the Simple dialer fork has it where you put up the API key of Truecaller account and you're good to go)
  - When you open dialer and click search, it should also recommend contacts from the contact list instead of showing nothing
  - Latest beta 4.8.3 crashes when clicked on loud speaker (You need to have Bluetooth turned on and device connected like a smart watch or an ear phone)
- Gallery
  - MaterialYou Themed icon looks bad and is completely different from the actual icon (I'm not sure whether it is the default launcher doing it but yeah)
  - Built in video edit support
  - Optionally, GPhotos like advanced editing tools with MLKit (I've no idea on how hard it is to achieve but most of them work offline)
- Files -- I've no idea whether this app is is being maintained or not (Material Files has these so refer the implementation)
  - Backup and Restore 
  - Amoled black with MaterialYou 
  - FTP
  - APK Achieve viewer
  - Option to add more storage options such as Cloud additions (Filen, GDrive, RClone, WebDav pCloud), USB, etc., 
  - More customisation option w.r.t folder designs and all those stuff

And finally, all these apps would work great if they've better integration to system like Google apps have (AFAIK, they interact with GMS to get their things done, but I run a different OS that does not have Google apps and yet they (Google clock, Maps, Dialer without GMS) work great ).

**Comment by Turhvjbufv** [comment]
Why closed?

**Comment by heckarman** [comment]
I don't think this is possible, at least in the coming days and even the dev did not care respond to this in the last 2+ weeks.

I would want to implement these features if time permits me to do so (I do not want to sound like a beggar either given my previous encounters asking for features).
